Attribute chooser improvements
Esri/cityengine_for_rhino pull request #54
Opened 2023-06-01 14:25 UTC by lor11212

This PR modifies the attribute chooser dialog to separate the rule attribute in tabs for each imported rule.
![image](https://github.com/Esri/puma/assets/81747273/a11b4a7c-2f09-407d-b869-ef23bc104276)

The dialog is now having multiple tabs, one for the main rule, and additional tabs if there are attributes imported from other rule files.

The attributes are separated by groups and subgroups.

This PR is also slightly modifying the sorting of attributes to try and match CE, however, I did not manage to replicate the exact same order. I could not figure it out. Maybe you can have a look ?

2023-06-09 13:33 UTC, mistafunk requested changes
* Fixed a bug for the case of attributes without groups (out of sync attribute list passed from native API to GH)
* Improved the layout of the Attribute Form (replaced top level flow with table)
* Removed the style prefix from the import tab name
* Excluded the style prefix from the incremental attribute search
* Registered the enter/esc keys for ok/cancel buttons

2023-06-14 09:36 UTC, lor11212 reviewed
Code and functionality looks good. I have to minor things:
![image](https://github.com/Esri/puma/assets/81747273/58e9e910-1918-4e9e-862d-99ab64b08520)
1. I was not able to solve this small miss-alignment issue.
2. Should we add a bit more space at the between the tab names ?

2023-06-14 09:36 UTC, lor11212 commented on PumaGrasshopper/RuleAttribute.cs
> +        public string getImport() => Utils.getImportPrefix(mFullName);
We can remove this function, as it is  not used anymore.

2023-06-20 13:53 UTC, mistafunk commented
> Code and functionality looks good. I have to minor things: ![image](https://user-images.githubusercontent.com/81747273/245746967-58e9e910-1918-4e9e-862d-99ab64b08520.png)
> 
> 1. I was not able to solve this small miss-alignment issue.
> 2. Should we add a bit more space between the tab names ?

I've tweaked the UI a bit more:

![MicrosoftTeams-image](https://github.com/Esri/puma/assets/1630632/d576cf9d-1112-4074-b5ce-a8cac5104444)

2023-06-20 13:54 UTC, merged